#################################################################
###################### Hexo Configuration #######################
#################################################################

title: PenZ's Space
subtitle: 万物归一
description:
keywords: blog
author: PenZ
language: zh-CN

index_generator:
  per_page: 6
  order_by: -date

archive_generator:
  per_page: 12
  yearly: true
  monthly: true
  daily: false

category_generator:
  per_page: 5

tag_generator:
  per_page: 5
  enable_index_page: false

timezone: Asia/Shanghai

url: http://yoursite.com
root: /
permalink: :title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives/
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

skip_render:
  - 'robots.txt'

new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

default_category: uncategorized
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss

per_page: 5
pagination_dir: page

theme: next

deploy:
  type: git
  repo: git@github.com:ShowPenZ/ShowPenZ.github.io.git
  branch: gh-pages
  message: "Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

server:
  port: 4000

marked:
  # For preserve original quotes in code blocks.
  smartypants: false

search:
  path: search.json
  field: all

symbols_count_time:
  symbols: false
  time: false
  total_symbols: false
  total_time: false
  awl: 4
  wpm: 275


#################################################################
###################### NexT Configuration #######################
#################################################################

theme_config:

  # ============================================================= #
  # ============= Theme Core Configuration Settings ============= #
  # ============================================================= #

  custom_file_path:
    sidebar: source/_data/sidebar.swig
    footer: source/_data/footer.swig
    variable: source/_data/variables.styl
    style: source/_data/styles.styl


  # ============================================================= #
  # ================= Site Information Settings ================= #
  # ============================================================= #

  footer:
    since: 2014
    icon:
      name: fa fa-heart
      animated: true
      color: "#808080"
    copyright: NexT
    powered: false

  creative_commons:
    license: by-nc-sa
    sidebar: true


  # ============================================================= #
  # ====================== Scheme Settings ====================== #
  # ============================================================= #

  # scheme: Muse
  # scheme: Mist
  # scheme: Pisces
  scheme: Gemini

  darkmode: true


  # ============================================================= #
  # ======================= Menu Settings ======================= #
  # ============================================================= #

  menu:
    home: / || fa fa-bullhorn

    # Docs:
    #   default: /docs/ || fa fa-book

    #   Getting Started:
    #     default: /getting-started/ || fa fa-flag
    #     Installation: /installation.html || fa fa-download
    #     Deployment: /deployment.html || fa fa-upload
    #     Configuration: /configuration.html || fa fa-wrench
    #     Update from 5.x: /update-from-v5.html || fa fa-retweet

    #   Theme Settings:
    #     default: /theme-settings/ || fa fa-star
    #     Footer: /footer.html || far fa-sun
    #     Sidebar: /sidebar.html || fa fa-bars
    #     Posts: /posts.html || far fa-edit
    #     Custom Pages: /custom-pages.html || far fa-file-alt
    #     Custom Files: /custom-files.html || far fa-file
    #     SEO: /seo.html || fa fa-external-link-square-alt
    #     Front Matter: /front-matter.html || fa fa-heading

    #   Third Party Services:
    #     default: /third-party-services/ || fa fa-plug
    #     Math Equations: /math-equations.html || fa fa-superscript
    #     Comment Systems: /comments.html || far fa-comments
    #     Statistics and Analytics: /statistics-and-analytics.html || fa fa-chart-bar
    #     Post Widgets: /post-widgets.html || fa fa-share-square
    #     Search Services: /search-services.html || fa fa-search-plus
    #     Chat Services: /chat-services.html || fa fa-comment
    #     External Libraries: /external-libraries.html || fa fa-puzzle-piece

    #   Tag Plugins:
    #     default: /tag-plugins/ || fa fa-rocket
    #     Note: /note.html || fa fa-comment
    #     Tabs: /tabs.html || fa fa-columns
    #     PDF: /pdf.html || far fa-file-pdf
    #     Mermaid: /mermaid.html || fa fa-tasks
    #     Label: /label.html || fa fa-font
    #     Video: /video.html || fa fa-video
    #     Button: /button.html || fa fa-square
    #     Caniuse: /caniuse.html || fa fa-signal
    #     Group Pictures: /group-pictures.html || far fa-file-image

    #   Advanced Settings: /advanced-settings.html || fa fa-cogs
    #   FAQ's: /faqs.html || fa fa-life-ring
    #   Troubleshooting: /troubleshooting.html || fa fa-bug
    # archives: /archives/ || fa fa-archive
    #sitemap: /sitemap.xml || fa fa-sitemap
    #commonweal: /404/ || fa fa-heartbeat

  menu_settings:
    icons: true
    badges: true


  # ============================================================= #
  # ===================== Sidebar Settings ====================== #
  # ============================================================= #

  sidebar:
    position: left
    display: post
    padding: 18
    offset: 12
    onmobile: true

  avatar:
    url: /images/avatar.jpg
    rounded: true

  social:
    GitHub: https://github.com/ShowPenZ || fab fa-github
    E-Mail: mailto:pengxiaoz1012@gmail.com || fa fa-envelope

  social_icons:
    enable: true
    icons_only: true
    transition: true

  toc:
    enable: true
    number: true
    wrap: true


  # ============================================================= #
  # ======================= Post Settings ======================= #
  # ============================================================= #

  post_meta:
    updated_at:
      enable: false

  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: true

  post_edit:
    enable: true
    url: https://github.com/theme-next/theme-next.org/edit/source/source/


  # ============================================================= #
  # ==================== Misc Theme Settings ==================== #
  # ============================================================= #

  mobile_layout_economy: true

  codeblock:
    highlight_theme: night bright
    copy_button:
      enable: true
      show_result: true
      style: default

  back2top:
    enable: true
    sidebar: false
    scrollpercent: true

  github_banner:
    enable: true
    permalink: https://github.com/theme-next/hexo-theme-next
    title: Fork NexT on GitHub


  # ============================================================= #
  # ======================= SEO Settings ======================== #
  # ============================================================= #

  index_with_subtitle: true

  exturl: true

  yandex_site_verification: 3ac9ae36ddebb425


  # ============================================================= #
  # =============== Third Party Services Settings =============== #
  # ============================================================= #

  math:
    per_page: true
    mathjax:
      enable: true

  pjax: true

  mediumzoom: true

  lazyload: true


  # ============================================================= #
  # =================== Comments and Widgets ==================== #
  # ============================================================= #

  comments:
    lazyload: true

  disqus:
    enable: true
    shortname: theme-next
    count: true


  # ============================================================= #
  # ================= Statistics and Analytics ================== #
  # ============================================================= #


  # ============================================================= #
  # ====================== Search Services ====================== #
  # ============================================================= #

  local_search:
    enable: true
    trigger: auto
    top_n_per_article: 1


  # ============================================================= #
  # ======================== Tag Plugins ======================== #
  # ============================================================= #

  note:
    style: simple
    icons: true
    light_bg_offset: -3

  tabs:
    transition:
      tabs: true
      labels: true


  # ============================================================= #
  # ==================== External Libraries ===================== #
  # ============================================================= #

  motion:
    enable: false

  vendors:
    anime: //cdn.jsdelivr.net/npm/animejs@3/lib/anime.min.js
    fontawesome: //cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css
    pjax: //cdn.jsdelivr.net/gh/theme-next/theme-next-pjax@0/pjax.min.js
